### PR TITLE
Collision detection

### PR DESCRIPTION
**Pull request by JKamue**

### CODE REVIEW

**Comment by PhilHawk03** [comment]
works with rockets colliding into earth, but not with rockets colliding into other rockets 
anyway: Great work

**Comment by PhilHawk03** [comment]
Nur bei mehrern Raketen kann es nervig sein, dass es die benachrichtigung vom Crash für alle anzeigt

**Comment by Nalsai** [comment]
Merged just as I was writing my feedback

**Comment by JKamue** [comment]
Sorry for that, I just wanted to move forward in order to start working on the BigInteger System. I actually did some commits to improve the next rocket selection right after the merge. Maybe they implemented the enhancement you mentioned above

**Pull request merged**
