### PR TITLE
Implemented #45, OrbitScreen now has zoom via scroll wheel

### PR DESCRIPTION
**Pull request by JKamue**

### CODE REVIEW

**Comment by Nalsai** [comment]
Looks good. I will merge it if @PhilHawk03 gives his approval

**Comment by PhilHawk03** [comment]
Looks good. One more idea for the future: Zoom not "arround" the rocket, but arround the mouse. return to the rocket by pressing a button like "R"

**Comment by JKamue** [comment]
> Looks good. One more idea for the future: Zoom not "arround" the rocket, but arround the mouse. return to the rocket by pressing a button like "R"

That's a great idea but pretty hard to implement. You could open a seperate issue for that if you want to.

**Comment by PhilHawk03** [comment]
New idea --> [Feature] [Orbit Screen] improve the zoom #62

**Pull request merged**
